name: Publish Plugin

# Controls when the action will run. 
on: [workflow_dispatch]
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Publish Plugin
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Plugin
        env: 
          publish_token: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
